@startuml diagramma_videoconsumer
start
:Inizializza array circolari, costanti e variabili;
repeat
    if (VideoProducer è accessibile?) then (Si)
        if (_end_event non è impostato?) then (Si)
            if (Evento _is_running impostato?) then (Si)
                :Acquisisci frame dal VideoProducer;
                :Converti frame in spazio colori HSV;
                :Ricava maschera di circolarità;
                :Memorizza maschera in balls_mask_history;
                if (balls_mask_history contiene tre elementi?) then (Si)
                    :Analisi del movimento sui tre frame;
                    :Memorizza stato di movimento in motion_history;
                    if (motion_history contiene NUMBER_OF_MOTION_COUNT valori?) then (Si)
                        if (motion_history contiene il 70% di valori True?) then (Si)
                            :new_motion_state = True;
                        else (No)
                            :new_motion_state = False;
                        endif
                        if (new_motion_state diverso da old_motion_state?) then (Si)
                            :Calcola timestamp corrente: current_time;
                            if ((current_time - last_state_change_time) > MIN_STATE_CHANGE_INTERVAL) then (Si)
                                :last_state_change_time = current_time;
                                :old_motion_state = new_motion_state;
                                if (old_motion_state è True?) then (Si)
                                    :Richiama start_movement_callback;
                                else (No)
                                    :Richiama stop_movement_callback;
                                endif
                            else (No)
                            endif
                        else (No)
                        endif
                    else (No)
                    endif
                else (No)
                endif
            else (No)
                :Svuota array circolari;
            endif
        else (No)
            stop
        endif
    else (No)
        stop
    endif
repeat while (VideoProducer è accessibile AND _end_event non è impostato?)
end
@enduml
